name: clube_parceria_tre_ma


description: Clube de Parcerias TRE-MA.

dependencies:
 flutter:
  sdk: flutter
 cupertino_icons: ^0.1.1
 flutter_search_bar: any
 path_provider: "^0.4.0"
 rxdart: "^0.16.7"
 fluro: "^1.3.1"
 debounce: "^0.1.0"
 ##material_search: ^0.2.4

# flutter_launcher_icons: ^0.3.2

#flutter_icons:
#  image_path: "icon/icon.png"
#  android: true
#  ios: true

dev_dependencies:
  flutter_test:
   sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/data/partners.json
    - assets/images/logo.png
    - assets/images/logo-tre-ma.png
    - assets/images/service.png