name: clube_parceria_tre_ma
description: Clube de Parcerias TRE-MA.
dependencies:
 flutter:
  sdk: flutter
 cupertino_icons: ^0.1.1
dev_dependencies:
  flutter_test:
   sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/data/partners.json
    - assets/images/logo.png
    - assets/images/logo-tre-ma.png
    - assets/images/service.png